<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="39" started-at="2017-07-21T16:38:36Z" finished-at="2017-07-21T16:38:36Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="39" started-at="2017-07-21T16:38:36Z" finished-at="2017-07-21T16:38:36Z">
      <class name="ngpackage.testng1stpgm">
        <test-method status="FAIL" signature="login()[pri:1, instance:ngpackage.testng1stpgm@190c9c3]" name="login" duration-ms="11" started-at="2017-07-21T22:08:36Z" description="login application" finished-at="2017-07-21T22:08:36Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [13] but found [12]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [13] but found [12]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:388)
	at org.testng.Assert.assertEquals(Assert.java:398)
	at ngpackage.testng1stpgm.login(testng1stpgm.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="select()[pri:2, instance:ngpackage.testng1stpgm@190c9c3]" name="select" duration-ms="2" started-at="2017-07-21T22:08:36Z" description="itemselem" finished-at="2017-07-21T22:08:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- select -->
        <test-method status="PASS" signature="checkout()[pri:3, instance:ngpackage.testng1stpgm@190c9c3]" name="checkout" duration-ms="1" started-at="2017-07-21T22:08:36Z" finished-at="2017-07-21T22:08:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkout -->
      </class> <!-- ngpackage.testng1stpgm -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
